# Generated by Django 4.1.3 on 2022-12-02 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='date_modified',
        ),
        migrations.AddField(
            model_name='todo',
            name='modified_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
